### ISSUE TITLE
No header files - boost/*.hpp

### ISSUE THREAD

**Issue by GuardNexusGN** [grenom/getsysinfo#1]
Can not compile project without boost/*.hpp source files, will be very thankful for those files in master.

A little list here:
<boost/program_options.hpp>
<boost/regex.hpp>
<boost/format.hpp>
<boost/property_tree/ptree.hpp>
<boost/property_tree/json_parser.hpp>

**Comment by grenom** [comment]
This source files belong [Boost C++ Libraries](https://www.boost.org/). If you need build in you own - first you should build Boost C++ Libraries and then build this repo.
if you don't want it, you can download my build - x64/Release or Release in this repository.

**Comment by GuardNexusGN** [comment]
Thanks for info, ill try to build library
